### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by minons1** [asos-craigmorten/opine#110]
Setup:

- deno 1.9.0 (release, x86_64-pc-windows-msvc)
- v8 9.1.269.5
- typescript 4.2.2
- Opine 1.2.0

## Details

Hi, I'm trying to run getting started code from [opine deno land](https://deno.land/x/opine@1.2.0), but I got this error message
![image](https://user-images.githubusercontent.com/55347970/114705612-1c250780-9d52-11eb-926a-2c9052a8edf2.png)

Is there any problem I am facing, any solution that may work? thank you in advance

**Comment by asos-craigmorten** [comment]
Hi @minons1 👋 

It seems something changed between `1.8.3` and `1.9.0` of Deno which resulted in the Opine response object missing a fundamental property which causes this error.

I've released a new version `1.3.0` which hopefully resolves this issue - let me know if you still are having issues with the new release and we can reopen this issue! 🙃

**Comment by minons1** [comment]
thank you @asos-craigmorten for your help, it works perfectly now 😎

**Comment by asos-craigmorten** [comment]
Awesome 🎉 great to hear! 😄
