### ISSUE TITLE
Exported middleware causing error in latest version

### ISSUE THREAD

**Issue by rssaranece94** [asos-craigmorten/opine#114]
# Issue

Setup:

- Deno Version: <1.9.0>
- v8 Version: <9.1.269.5>
- Typescript Version: <4.2.2>
- Opine Version: <1.3.2>

## Details

log.ts
```
export const logErrors = (error: any, req: Request, res: Response, next: NextFunction) => {
  console.error(error.stack);
  next(error);
};
```

app.ts
```
import { logErrors } from './log.ts';
...
app.use(logError);

```

error: TS2612 [ERROR]: Property 'resolve' will overwrite the base property in 'Deferred<undefined>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    public readonly resolve!: () => void;
                    ~~~~~~~
    at https://deno.land/x/evt@v1.9.12/tools/Deferred.ts:57:21


kindly help me out of it

**Comment by asos-craigmorten** [comment]
Hi @rssaranece94 👋 

I'm struggling to reproduce 😢  - I have created an `app.ts`

```ts
import { opine } from "https://deno.land/x/opine@1.3.2/mod.ts";
import { logErrors } from "./log.ts";

const app = opine();

app.use(() => {
  throw new Error("test-error");
});

app.use(logErrors);

app.listen(3000);
```

and a `log.ts`

```ts
import type { Request, Response, NextFunction } from "https://deno.land/x/opine@1.3.2/mod.ts";

export const logErrors = (
  error: any,
  req: Request,
  res: Response,
  next: NextFunction,
) => {
  console.error(error.stack);
  next(error);
};
```

And can see the server is working as expected.

It is curious that you are getting an error thrown from the `evt` library as that was removed as a dependency from Opine in version `1.2.0` ( see https://github.com/asos-craigmorten/opine/blob/main/.github/CHANGELOG.md#120---06-03-2021 ). Please check that you are using the latest version of Opine `1.3.2` in all of your code, and if that isn't resolving the issue, perhaps try using the `--reload` flag when you next run the app to refetch dependencies in case something has happened to corrupt your Deno cache.

If none of this fixes the issue, please could you provide a fuller example of the exact code that is not working for you, or share a gist / repo etc? 😄

**Comment by rssaranece94** [comment]
Thanks for the help. Sorry my bad I missed old version import in sub files. Updated those works well.

**Comment by asos-craigmorten** [comment]
Ah, glad you were able to sort it 🎉 nice one 😄
