### ISSUE TITLE
[FEAT] Adopt Native HTTP Server

### ISSUE THREAD

**Issue by asos-craigmorten** [asos-craigmorten/opine#115]
# Issue

## Details

In Deno `1.9.0` ( https://github.com/denoland/deno/releases/tag/v1.9.0 ) native HTTP bindings were introduced to Deno ( https://github.com/denoland/deno/pull/9935 ) allowing for potential performance improvements, and opening the path towards HTTP2 support and other features.

This issue is to adapt Opine to support the new HTTP setup.

See Oak as an example:

- https://github.com/oakserver/oak/commit/59e7a002333be07c56854e0b69f41269ead43eb2
- https://github.com/oakserver/oak/commit/96373acb2b9457f323bad0b9cf182c82c3b0bd8e

Ideally we either support both old and new with either an adaptor based on feature detection or flag ( or a combination of both ), or we wait for the feature to become stable and then adopt with a new major.

**Comment by janusz-f** [comment]
I can help you with adoptation to native HTTP
