### ISSUE TITLE
res.cookie maxAge can't be 0

### ISSUE THREAD

**Issue by 4ov** [asos-craigmorten/opine#125]
# Issue

Setup:

- Deno Version: 1.11.0 (release, x86_64-unknown-linux-gnu)
- v8 Version: 9.1.269.35
- Typescript Version: 4.3.2
- Opine Version: 1.4.0

## Details

`res.cookie`'s `maxAge` option can be 0 in express while it's giving an error in opine

```js
error: Uncaught (in promise) DenoStdInternalError: Max-Age must be an integer superior to 0
  if (!expr) {
           ^
    at assert (https://deno.land/std@0.97.0/_util/assert.ts:12:12)
    at toString (https://deno.land/std@0.97.0/http/cookie.ts:60:5)
    at setCookie (https://deno.land/std@0.97.0/http/cookie.ts:180:13)
    at Response1.cookie (https://deno.land/x/opine@1.4.0/src/response.ts:142:5)
```

**Comment by cmorten** [comment]
Looks like this error is coming from the std lib. 

REF: https://deno.land/std@0.98.0/http/cookie.ts#L60

The git blame takes you to a PR where the author states that 0 is valid ( well, says negative values are invalid ) according to the RFC ( https://github.com/denoland/deno_std/pull/359#discussion_r279169244 ).

Indeed, the RFC states:

> Max-Age=delta-seconds
>      Optional.  The Max-Age attribute defines the lifetime of the
>      cookie, in seconds.  The delta-seconds value is a decimal non-
>      negative integer.  After delta-seconds seconds elapse, the client
>      should discard the cookie.  A value of zero means the cookie
>      should be discarded immediately.

REF: https://www.ietf.org/rfc/rfc2109.txt

So think this is a mistake in the http std lib - can you also raise an issue there?

**Comment by asos-craigmorten** [comment]
This has been fixed upstream, awaiting next `deno_std` release.

REF: https://github.com/denoland/deno_std/pull/992

**Comment by 4ov** [comment]
So we are good here, Thanks.
