### ISSUE TITLE
OPTIONS related tests failing as response no longer has a body

### ISSUE THREAD

**Issue by cmorten** [asos-craigmorten/opine#132]
# Issue

Setup:

```console
deno 1.11.4 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

## Details

Tests are failing on the `1.11.x` Deno versions because `fetch` has been updated to no longer return a `body` in it's `response`.

REFs:
- https://github.com/denoland/deno/issues/10990
- https://github.com/denoland/deno/pull/11003

**Comment by asos-craigmorten** [comment]
PR raised for fix: https://github.com/denoland/deno/pull/11242
