### ISSUE TITLE
Ipaddr does not provide an export named 'default

### ISSUE THREAD

**Issue by MrWindwaker** [asos-craigmorten/opine#137]
# Issue

Setup:

- Deno Version: 1.12.2
- v8 Version: 9.2.230.14
- Typescript Version: 4.3.5
- Opine Version: 1.7.0

## Details

error: Uncaught SyntaxError: The requested module 'https://esm.sh/ipaddr.js@2.0.0' does not provide an export named 'default'
export { default as ipaddr } from "https://esm.sh/ipaddr.js@2.0.0";
         ~~~~~~~~~~~~~~~~~
    at <anonymous> (https://deno.land/x/opine@1.7.0/deps.ts:54:10).

**Comment by cmorten** [comment]
Hmm, can’t reproduce with that error, but am seeing 408 timeouts when try to access that asset via esm.sh - wonder if the CDN is having issues 🤔

**Comment by cmorten** [comment]
Have reproduced reliably now - curious as nothing has changed from Opine's side - indeed CI passed for this version, importing this dep etc.

From what understand `esm.sh` maps to a mutable `cdn.esm.sh/v*` like url, and suspect that a version has revved and introduced a regression. It doesn't appear that you can fix the version of `esm.sh` that you use as it just bounces you, so we are suspectible to breaking changes. Going to give migrating to skypack a go.
