### ISSUE TITLE
Incompatible with Deno 1.13.0

### ISSUE THREAD

**Issue by TheAifam5** [asos-craigmorten/opine#139]
# Issue

Setup:

- Deno Version: 1.13.0
- v8 Version: 9.3.345.11
- Typescript Version: 4.3.5
- Opine Version: 1.7.1

## Details
Deno updated error definitions which is incompatible with `http_errors` (i suspect). Has been introduced in https://github.com/denoland/deno/pull/10702
The error message I get:
```
error: TS2416 [ERROR]: Property 'name' in type 'PartialReadError' is not assignable to the same property in base type 'UnexpectedEof'.
  Type 'string' is not assignable to type '"UnexpectedEof"'.
  name = "PartialReadError";
  ~~~~
    at https://deno.land/std@0.69.0/io/bufio.ts:26:3
```

**Comment by hmt** [comment]
Yikes, Google didn't find this issue. I had to `deno upgrade --version 1.12.2` and it works again.

**Comment by thunderk** [comment]
I opened an issue on http_errors for it: https://github.com/ako-deno/http_errors/issues/4

I think that `accepts` should also be bumped, as they released a fix for this problem as well: https://github.com/ako-deno/accepts/blob/2.1.1/History.md

**Comment by cmorten** [comment]
Slipped on my phone and closed 😅

Great sleuthing @thunderk - maybe we can raise a PR to fix http_errors and then hopefully can get something raised to make the various dep upgrades to opine.

**Comment by thunderk** [comment]
PR is ready for `http_errors` (https://github.com/ako-deno/http_errors/pull/5), waiting for a merge.
Once its done, I can propose a PR here with the deps upgrades.

**Comment by ngdangtu-vn** [comment]
> Yikes, Google didn't find this issue. I had to `deno upgrade --version 1.12.2` and it works again.

I wish I could do that. I got os error 5 (permission denied in Windows 10 - yep even I ran powershell as admin) and now I'm stuck!. Cannot backward and cannot forward... I guess see you guys next year?

**Comment by cmorten** [comment]
> > Yikes, Google didn't find this issue. I had to `deno upgrade --version 1.12.2` and it works again.
> 
> I wish I could do that. I got os error 5 (permission denied in Windows 10 - yep even I ran powershell as admin) and now I'm stuck!. Cannot backward and cannot forward... I guess see you guys next year?

If you are unable to use the `deno upgrade --version` flag on Windows 10 I would definitely report that as an issue on https://github.com/denoland/deno/issues

**Comment by cmorten** [comment]
Going by https://github.com/denoland/deno/issues/11713#issuecomment-899049214 we might be lucky and will be resolved in Deno core in a patch release today. Upgrading the deps is still a good exercise to do.
