### ISSUE TITLE
Incompatible with Deno 1.14.0

### ISSUE THREAD

**Issue by WayneChang65** [asos-craigmorten/opine#143]
# Issue

Setup:

- Deno Version: 1.14.0 (release, x86_64-apple-darwin)
- v8 Version: 9.4.146.15
- Typescript Version: 4.4.2
- Opine Version: 1.7.2

## Details

It seems incompatible with Deno 1.14.0.
I run the example and the result shows below.

## Deno 1.14.0 Error occured
<img width="1280" alt="截圖 2021-09-21 14 28 05" src="https://user-images.githubusercontent.com/33888917/134122153-01f3fbff-4841-48de-8dcb-8d911dfedc96.png">
...
<img width="1265" alt="截圖 2021-09-21 14 28 25" src="https://user-images.githubusercontent.com/33888917/134122190-e6567a96-0467-474f-985f-44567ddffc8e.png">

## Deno 1.13.2 is OK
<img width="1280" alt="截圖 2021-09-21 14 32 28" src="https://user-images.githubusercontent.com/33888917/134122609-820b4706-c836-46c7-ae39-2025694edeeb.png">

**Comment by cmorten** [comment]
Hey @WayneChang65 👋 

For now you can work around the issue with `std@0.105.0` being incompatible with Deno `1.14.0` by using the `--no-check` flag.

We just need to upgrade some of the deps to unblock this - problem with the std lib not being stable yet!

**Comment by WayneChang65** [comment]
OK. Thanks for the great project.

**Comment by cmorten** [comment]
Reopening until change CI to test on 1.14.0 and release the fox to a tag.

**Comment by cmorten** [comment]
@WayneChang65 please see https://deno.land/x/opine@1.8.0 which should resolve the issue.
