### ISSUE TITLE
[CHORE] Change the new default branch in Deno registry

### ISSUE THREAD

**Issue by sandeshdamkondwar** [asos-craigmorten/opine#19]
# Issue

Deno's Third Party modules registry still have master branch as a default branch, please change the default branch to "main". My PR got rejected because I'm not the owner of Opine.

## Details

<img width="1072" alt="Screenshot 2020-06-20 at 8 21 13 PM" src="https://user-images.githubusercontent.com/2510560/85222841-e20e0200-b3db-11ea-8cfb-e604fed41fc1.png">

**Comment by asos-craigmorten** [comment]
@sandeshdamkondwar really sorry about this - an oversight on my part! I'm raising a PR now.

FYI Opine now also supports the https://nest.land registy - see https://nest.land/package/opine

This registry is less prone to these issues as versions are backed into a blockchain - I'll look to update Opine's readme to add instructions on usage, but should be as simple as importing `https://x.nest.land/opine@0.10.2/mod.ts`

**Comment by asos-craigmorten** [comment]
Please see: https://github.com/denoland/deno_website2/pull/1195

**Comment by asos-craigmorten** [comment]
This has been resolved 😄
