### ISSUE TITLE
[FEATURE] Add `app.param()` API

### ISSUE THREAD

**Issue by asos-craigmorten** [asos-craigmorten/opine#21]
# Issue

Add the `app.param()` API.

## Details

- Express Docs: https://expressjs.com/en/4x/api.html#app.param
- Express Code: https://github.com/expressjs/express/blob/master/lib/application.js#L309
- Opine Code: https://github.com/asos-craigmorten/opine/blob/main/src/application.ts#L229

**Comment by abbasogaji** [comment]
@asos-craigmorten  Permit me to take this up

**Comment by asos-craigmorten** [comment]
Go for it @abbasogaji 😄

**Comment by abbasogaji** [comment]
@asos-craigmorten, oh great thanks, i made a PR already .🙂
