### ISSUE TITLE
[FEATURE] Capture errors from async routes

### ISSUE THREAD

**Issue by gumberss** [asos-craigmorten/opine#34]
# Issue

Setup:
- 
- Deno Version: 1.1.1
- v8 Version: <replace_with_v8_version>
- Typescript Version: <replace_with_typescript_version>
- Opine Version: main

If you throw an error in an async route, this error won't be caught for an error route

## Details

The error:
![](https://user-images.githubusercontent.com/38296002/85964347-b8327d80-b98f-11ea-8c40-573a1dc5dfb7.png)

The code:

![](https://user-images.githubusercontent.com/38296002/85964389-e0ba7780-b98f-11ea-802c-cc0b1ced6d73.png)

The result expected:

![](https://user-images.githubusercontent.com/38296002/85964374-d13b2e80-b98f-11ea-8e15-eed66496f7bb.png)

**Comment by asos-craigmorten** [comment]
Decided this is more of a feature than a bug given it isn't handled behaviour in Express either. However, I very much welcome the change 😄

**Comment by gumberss** [comment]
Oh no!!! I just noticed I used the 'express-async-errors' in my project (facepalm). Yes, it is a feature hahahaha, sorry
