### ISSUE TITLE
Error executing sample script from https://deno.land/x/opine

### ISSUE THREAD

**Issue by rglowrey** [asos-craigmorten/opine#39]
# Issue

Setup:

- Deno Version: 1.1.2
- v8 Version: 8.5.216
- Typescript Version: 3.9.2
- Opine Version: opine@main/mod.ts
- (environment variable) DENO_INSTALL=/home/rick/.deno 
 
> Error when executing deno sample script from https://deno.land/x/opine

## Details

> I saved the sample script with name "sampleOpine.ts", then executed it as below.  It threw an error as follows:

deno run sampleOpine.ts
Check file:///home/rick/Working/Playpen/deno/OpineTemplate/sampleOpine.ts
error: TS2305 [ERROR]: Module '"./_utils"' has no exported member 'normalizeEncoding'.
import { notImplemented, normalizeEncoding } from "./_utils.ts";
                         ~~~~~~~~~~~~~~~~~
    at https://deno.land/std/node/buffer.ts:3:26

Not quite sure what to do with this, or if it's my configuration that's the problem.  NB: I was able to successfully run a Deno server app using OAK on the same machine.

**Comment by asos-craigmorten** [comment]
@rglowrey ah yes, saw this is in one of my other repos - one of the subdependencies hasn’t locked its versions causing this issue - I’ll get a patch out this morning shortly.

**Comment by asos-craigmorten** [comment]
@rglowrey please can you try out `0.17.0` and see if that is fixed for you? 🙂 

REF: https://github.com/asos-craigmorten/opine/releases/tag/0.17.0

**Comment by rglowrey** [comment]
No, didn't fix it.

Here's the code I ran:
```
import { opine } from "https://deno.land/x/opine@0.17.0/mod.ts";

const app = opine();

app.use((req, res) => {
  res.send("Hello World");
});

app.listen(3000);

```
Here's the result:
```
rick@rick-XPS-8920:~/Working/Playpen/deno/OpineTemplate$ deno run --allow-net sampleOpine.ts
Check file:///home/rick/Working/Playpen/deno/OpineTemplate/sampleOpine.ts
error: TS2305 [ERROR]: Module '"./_utils"' has no exported member 'normalizeEncoding'.
import { notImplemented, normalizeEncoding } from "./_utils.ts";
                         ~~~~~~~~~~~~~~~~~
    at https://deno.land/std/node/buffer.ts:3:26
```

**Comment by asos-craigmorten** [comment]
Hmm... the classic and somewhat unhelpful "works for me"!

Can you try with the `--reload` flag? I wonder if you've got a cached "bad" subdependency somewhere? I.e.

```console
$ deno run --allow-net --allow-read --reload sampleOpine.ts
```

**Comment by rglowrey** [comment]
Now I get to give the classic "so it really WAS me all along!".  Yes, running with the --reload flag did the trick.  Also, when I ran it with the first line 
`import { opine } from "https://deno.land/x/opine@main/mod.ts";`
it worked fine after that --reload.  Thanks for your help, and sorry for the bother.

**Comment by asos-craigmorten** [comment]
@rglowrey no bother at all! I believe the initial problem lay with Opine :joy: or specifically one of it's dependencies - something I think needs ironed out in Deno is sub-dependency resolution, conflicts etc. I don't think there is a way to "lock" versions for consumers of a module. The only thing consumers can do afaik is find a "good" version and then use the `--lock-write` and subsequently `--lock` flags to protect themselves from these errors - I don't think it can be fixed upstream just yet...?

Glad it works now anyway!
