### ISSUE TITLE
[FEAT] Support GZIP and Deflate Compression

### ISSUE THREAD

**Issue by asos-craigmorten** [asos-craigmorten/opine#52]
# Issue

Setup:

Add support for deflate and gzip encoding in body-parsers.

## Details

Currently gzip and deflate are not supported in Opine and throw a `415` error. This issue is to add support to Opine for these two standard options which is now possible due to modules being made available in the Deno userland.

Relevant file: `./src/middleware/bodyParser/read.ts` Line 117.

Modules to explore:
- https://deno.land/x/wasm_gzip@v1.0.0
- https://deno.land/x/jszip@0.7.0
- https://deno.land/x/denoflate

**Comment by JayHelton** [comment]
@asos-craigmorten i think i will grab this one and give it a shot!

**Comment by JayHelton** [comment]
Im assuming this would be a deno idiomatic port of https://github.com/expressjs/body-parser/blob/master/lib/read.js?
