### ISSUE TITLE
[BUG] Cannot read property 'req' of undefined when using serveStatic function

### ISSUE THREAD

**Issue by futurelucas4502** [asos-craigmorten/opine#58]
# Issue

Setup:

- Deno Version: 1.3.0
- v8 Version: 8.6.334
- Typescript Version: 3.9.7
- Opine Version: 0.20.2

After following the tutorial for using Opine with dejs [here](https://dev.to/craigmorten/opine-tutorial-part-2-creating-a-website-in-deno-37o3) I get an issue where when I try and load the site it gives an error

Not sure if this is relevant but I'm running Windows 10 2004 x64

## Details

I installed deno using the following command in powershell: `iwr https://deno.land/x/install/install.ps1 -useb | iex`

I then followed the tutorial writing out all the code and went to run it using `deno run --allow-net --allow-env --allow-read=./ ./entrypoint.ts` however if I then try and load the page I get the following error displayed instead of my index page: 
![image](https://user-images.githubusercontent.com/48055553/90396978-0fe78e00-e08f-11ea-840f-d288645eb5bd.png)

## Exact code used

https://github.com/futurelucas4502/Opine-dejs

**Comment by asos-craigmorten** [comment]
@futurelucas4502 can you try and confirm you still have an issue after using a `--reload` flag, e.g.

```console
deno run --allow-net --allow-env --allow-read=./ --reload ./entrypoint.ts
```

If that fails, can you also see if you have an issue running with the following repo: https://github.com/asos-craigmorten/opine-template

This should be the repository created when following the tutorial.

Let me know how get on?

---

Slightly lost atm as I can't reproduce, but someone else has also had this issue now... This is my setup:

```
$ deno --version
deno 1.3.0
v8 8.6.334
typescript 3.9.7
````

on MacOS Mojave (10.14.6), so it could be OS related, but hard to be sure just yet!

**Comment by asos-craigmorten** [comment]
Pulled down your repo and it runs ok for me (once realised the default port was `80` not `3000` 😂 ). Steps:

```console
mkdir -p ~/git/futurelucas4502
cd ~/git/futurelucas4502
git clone git@github.com:futurelucas4502/Opine-dejs.git
deno run --allow-net --allow-env --allow-read=./ --reload ./entrypoint.ts
```

<img width="1552" alt="Screen Shot 2020-08-17 at 16 05 56" src="https://user-images.githubusercontent.com/46491566/90411391-9c9c4700-e0a3-11ea-8f3e-505496c31106.png">

<img width="1552" alt="Screen Shot 2020-08-17 at 16 06 02" src="https://user-images.githubusercontent.com/46491566/90411399-9f973780-e0a3-11ea-8a5b-bc8f0c3200c1.png">

**Comment by futurelucas4502** [comment]
I attempted using both the cloned repo and using the reload function the cloned repo is the screenshot below:
![image](https://user-images.githubusercontent.com/48055553/90424256-b6468a00-e0b5-11ea-8700-5fe7d3776040.png)

Using reload on my code is the screenshot:
![image](https://user-images.githubusercontent.com/48055553/90424286-ca8a8700-e0b5-11ea-9006-8689cda16817.png)

I have however found something which is very curious if I purposely make a 404 error by going to a random address the page loads with the 404 error and the static public directory with the stylesheet is also served correctly which is very odd indeed
![image](https://user-images.githubusercontent.com/48055553/90424416-ff96d980-e0b5-11ea-8044-3e37daab6332.png)

**Comment by futurelucas4502** [comment]
So after doing some more research it works completely fine on both Linux and MacOS therefore this seems to be an OS specific issue that only occurs on windows @asos-craigmorten

**Comment by asos-craigmorten** [comment]
@futurelucas4502 great work confirming! I suspect there may be some path manipulation logic that needs fixing somewhere, that is generally the cause of cross-OS issues

**Comment by asos-craigmorten** [comment]
Closed automatically with the linked PR #59 

@futurelucas4502 can you confirm whether `opine@0.21.1` resolves the issue or whether I've just fixed something unrelated :joy:

**Comment by asos-craigmorten** [comment]
Ok, I'm able to reproduce under different means on MacOS using the `static-files` example and navigating to `http://localhost:3000/js` which invokes the redirect directory listener and then errors with the same message as you have been seeing - will give fixing that a whirl and 🤞 it also solves your issue!

**Comment by asos-craigmorten** [comment]
@futurelucas4502 can you confirm whether `opine@0.21.2` resolves the issue?

**Comment by futurelucas4502** [comment]
hi @asos-craigmorten thanks for all your work I can confirm opine@0.21.2 fixes the problem and opine now works on windows properly!

**Comment by asos-craigmorten** [comment]
That’s awesome to hear! 🍾 please raise further issues if find anything else isn’t quite right 😄
