### ISSUE TITLE
Router in opine as in express

### ISSUE THREAD

**Issue by IrfanAli17899** [asos-craigmorten/opine#6]
# Issue

## Details

> Please add details of the feature / bug you wish to be addressed. If it is a bug please add steps to reproduce.
I think Opine does not contain Router just like in express if is it then please let us know
const { Router } = require('express'); 
what is its alternative in Opine thanks in advance.

**Comment by asos-craigmorten** [comment]
Hi @IrfanAli17899 please refer to the Opine docs on `Router`: https://github.com/asos-craigmorten/opine/blob/master/.github/API/router.md#routeroptions

You can also check out this example: https://github.com/asos-craigmorten/opine/tree/master/examples/multi-router

Overall, the `Router` is a named export of Opine which can be imported using:

```ts
import { Router } from "https://deno.land/x/opine@master/mod.ts";

const router = Router();
```

This is subtly different to Express when using `require` in commonjs. To ease transition I’ll raise a PR to also make these available on the Opine object itself.

**Comment by IrfanAli17899** [comment]
I know require is the part of commonjs here, deno is supporting ECMAScript, so will be imported just wanted to know about router thanks I got the answer :)
