### ISSUE TITLE
Add Eta template engine to examples

### ISSUE THREAD

**Issue by nebrelbug** [asos-craigmorten/opine#61]
This is a really cool project!

I'm the maintainer of the [Eta](https://eta.js.org) template engine, and I just added Deno support. I'd love to add an example of a server using Eta to the Opine examples. Could I submit a PR?

**Comment by asos-craigmorten** [comment]
Hey @nebrelbug 👋 

Yes please do! PRs are very welcome 😄 Let me know if need a hand with anything 🙂

**Comment by asos-craigmorten** [comment]
Closed by #65
