### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [asos-craigmorten/opine#66]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

If it is possible to use pagic to build the website, I would like to create the pull-request

**Comment by asos-craigmorten** [comment]
Hey @xcatliu :wave:

Pagic looks awesome - nice work 😄 

What are you suggesting we should be hosting using Pagic? For now GitHub pages, Deno Doc and markdown docs are doing reasonably well afaik for Opine, but could be missing something!
