### ISSUE TITLE
Create the project tasks for the project 

### ISSUE THREAD

**Issue by jvmazagao** [asos-craigmorten/opine#68]
Hello everyone, can we create a project board here to map everything we need to develop and fix?

**Comment by jvmazagao** [comment]
@asos-craigmorten

**Comment by asos-craigmorten** [comment]
Hey @jvmazagao :wave:

Sure, why not! I’ll try and put one together 😄

**Comment by asos-craigmorten** [comment]
See https://github.com/asos-craigmorten/opine/projects/1 for the beginnings of the v1 project. I will try to add some more tickets to the project to flesh it out later.

Let me know if this isn’t what you meant!

**Comment by jvmazagao** [comment]
This is what I meant,  now we can track better the issues, I will take a look in the board.

**Comment by asos-craigmorten** [comment]
Project has been fully populated now afaik for what's needed for v1 release 😄 

If there is anything you fancy working on then I really appreciate the help! 🚀

**Comment by jvmazagao** [comment]
@asos-craigmorten  can you give me permission to manage the board? I like to help with the documentation because I'm not very good with deno yet.
