### ISSUE TITLE
[FEAT] Support all Express options for file-related response APIs

### ISSUE THREAD

**Issue by asos-craigmorten** [asos-craigmorten/opine#75]
# Issue

Support full suite of Express options for the `sendFile()` and `download()` response APIs, as well as the `serveStatic()` API options.

## Details

Should support:

- abort handling
- directory handling
- error handling - see https://github.com/pillarjs/send/blob/master/index.js#L267
- `options` - see https://github.com/pillarjs/send#sendreq-path-options
- other headers: 'Accept-Ranges', 'Cache-Control', 'Content-Range'

See also https://github.com/expressjs/serve-static/#options

**Comment by jvmazagao** [comment]
Can we extract error handling and options for other issues? 

It's completely correlated but, we can deliver fast if we separate this task.
